name: Daily Auto Commit

on:
  schedule:
    # Runs twice a day at 04:30 and 16:30 UTC
    # Runs 4 times a day:
    # 02:45 WIB -> 19:45 UTC
    # 12:00 WIB -> 05:00 UTC
    # 18:00 WIB -> 11:00 UTC
    # 22:30 WIB -> 15:30 UTC
    - cron: "45 19 * * *"
    - cron: "0 5 * * *"
    - cron: "0 11 * * *"
    - cron: "30 15 * * *"
  workflow_dispatch: # Allows manual triggering

jobs:
  auto-commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Important for push

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Run Auto-Commit Script
        run: python autocommit.py
