name: Daily Auto Commit

on:
  schedule:
    # Runs twice a day at 04:30 and 16:30 UTC
    - cron: "30 4 * * *"
    - cron: "30 16 * * *"
  workflow_dispatch: # Allows manual triggering

jobs:
  auto-commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Important for push

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Configure Git
        run: |
          git config --global user.name "winterc0ldsye"
          git config --global user.email "winterc0ldsye@gmail.com"

      - name: Run Auto-Commit Script
        run: python autocommit.py
